### PR TITLE
Add security archives to sources list

### PR DESCRIPTION
**Pull request by paulmenzel**
Fixes: #9

### CODE REVIEW

**Comment by paulmenzel** [comment]
Sorry, that just works for Debian 8 (jessie/stable). :(

**Comment by jmtd** [comment]
I think using "stable/updates" would work for any release, and not be jessie specific, and I _think_ it would be harmless to have that included even for a sid or testing build (default apt pinning would mean it was just ignored). ~~An open question I have is whether we can adjust the `debootstrap` line to include that repo from the off rather than need the echo in the `Dockerfile`.~~

Edit: seems I'm wrong about `debootstrap`.

**Comment by paulmenzel** [comment]
Indeed, it does not seem possible with debootstrap. Therefore I am planning to move to grml-debootstrap, solving all™ the shortcomings of debootstrap.

**Comment by jmtd** [comment]
Sorry for the delay on this one. I'm just testing this fix to see how well it works with e.g. a sid image and should merge it soon (or a variant with stable named instead of jessie)

**Comment by jmtd** [comment]
I've got another possible fix [here](https://github.com/jmtd/debian-docker/commit/3d4f35d92f025283331efe6e3131143e6beb10af), which I'm just double-checking, testing and thinking about a bit harder.

**Comment by jmtd** [comment]
I've merged a slightly more robust approach to this, thanks for raising the issue and pointing me in the right direction!

**Pull request closed without merging**
