### PR TITLE
Purge autoremoved packages and exclude resolv.conf

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
@jmtd Could you please merge this?

**Comment by jmtd** [comment]
Hi, I am happy with `--purge` but I'm not sure why removing resolv.conf is a good idea.

**Comment by szepeviktor** [comment]
> Hi, I am happy with --purge but I'm not sure why removing resolv.conf is a good idea.

Because Docker bind-mounts that file.

**Comment by jmtd** [comment]
> Because Docker bind-mounts that file.

Sure, so the old copy in the filesystem is irrelevant. But why remove it? Is docker not bind-mounting during a build too -- I thought it was (each build step is executed as a container)

If the rationale is image size, this won't make the image smaller; but it will make the layer delta larger.

**Comment by szepeviktor** [comment]
> the rationale is

This file seems like trash, and it contains the builder's resolvers.

**Comment by szepeviktor** [comment]
> it will make the layer delta larger.

Yes. Could it be removed in the makefile?
https://github.com/jmtd/debian-docker/blob/master/Makefile#L37

**Comment by jmtd** [comment]
> This file seems like trash, and it contains the builder's resolvers.

Ah that's a good point, it could be a privacy problem to leak that into the images.

> Yes. Could it be removed in the makefile?

I think I prefer that. Could you please remove it from this PR (then I will happily apply this PR) and we can either raise a separate issue or a separate PR for the resolv.conf file.

Thanks for working on this! Sorry I haven't put much into it in recent times.

**Comment by szepeviktor** [comment]
Done.

**Pull request merged**
