### PR TITLE
Add getting started steps

### LINKED ISSUE #7: Can't exec /bin/sh on sudo make
```
voltagex@devbian:~/src/debian-docker$ sudo make prefix=voltagex mirror=http://mirror.internode.on.net/pub/debian/
mkdir jessie-amd64
cd roots/jessie-amd64 && tar cf ../../jessie-amd64/root.tar ./
sed 's/SUBSTITUTION_FAILED/17507b7e2d12126e95bf61c1c49ac79036687fcb/' Dockerfile.in >jessie-amd64/Dockerfile
docker build -t voltagex/debian:jessie-amd64 jessie-amd64
Sending build context to Docker daemon  12.8 kB
Step 0 : FROM scratch
 --->
Step 1 : MAINTAINER Jonathan Dowland <jmtd@debian.org>
 ---> Running in dd2a918e4d5a
 ---> 1a16ed6c5bc0
Removing intermediate container dd2a918e4d5a
Step 2 : ADD root.tar /
 ---> 06601edef268
Removing intermediate container d61f65c17538
Step 3 : RUN apt-get update     && apt-get -y upgrade   && apt-get -y autoremove        && apt-get clean        && find /var/lib/apt/lists -type f -delete
 ---> Running in 0d167cf7e7d0
[8] System error: exec: "/bin/sh": stat /bin/sh: no such file or directory

```

### PR DESCRIPTION
**Pull request by ghost**
Fixes #7. I need a hand to make this better as the use of a SUITE environment variable isn't right  - I just can't see how to execute the rules beginning with $(tag) on the command line.

### CODE REVIEW

**Comment by ghost** [comment]
Ping @jmtd

**Comment by jmtd** [comment]
Hi @voltagex , sorry for not getting back on this, I haven't had much time for it recently.

The default getting started action should just be "sudo make": there should be sensible defaults for all the parameters (although using `$USER` for prefix is an interesting idea) and the dependencies should be set up so that it all "just works". What I don't understand from your log in #7 is why the `debootstrap` step didn't run. I'll try running this again fresh and see if it does indeed work as I thought it did.

**Comment by n00dl3** [comment]
> What I don't understand from your log in #7 is why the debootstrap step didn't run.

I experienced the same issue but it was because I first launched the make command as non-root user. It created the directories the first time so the script couldn't continue after the mkdir -p :

``` Makefile
roots/$(tag):
    mkdir -p $@ \
        && debootstrap --arch $(arch) $(release) $@ $(mirror) \
        && chroot $@ apt-get clean
```

**Comment by jmtd** [comment]
I see: since the directory was created, that rule is "satisfied" and so re-running under root doesn't get you a filesystem.

**Pull request merged**
